# Generated by Django 3.2 on 2025-07-06 16:14

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.MaxLengthValidator(254)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.MaxLengthValidator(150)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.MaxLengthValidator(150)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.TextField(max_length=150, unique=True, validators=[users.validators.validate_not_forbidden_username, django.core.validators.RegexValidator(message='Имя пользователя содержит недопустимые символы', regex='^[\\w.@+-]+\\Z'), django.core.validators.MaxLengthValidator(150)]),
        ),
    ]
